CREATE TABLE IDENTITY_DETAILS (
	KYCNO BIGINT NOT NULL,
	CUSTOMER_NAME VARCHAR(48) NOT NULL,
	FS_NAME VARCHAR(48) NOT NULL,
	MARITAL_STATUS VARCHAR(7) NOT NULL,
	GENDER VARCHAR(6) NOT NULL,
	PAN VARCHAR(10) NOT NULL,
	AADHAR BIGINT NOT NULL,
	PRIMARY KEY (KYCNO)
);

CREATE TABLE ADDRESS_DETAILS (
	KYCNO BIGINT NOT NULL,
	HOME_ADDRESS VARCHAR(102) NOT NULL,
	CITY VARCHAR(48) NOT NULL,
	STATE_NAME VARCHAR(48) NOT NULL,
	POSTAL_CODE INT NOT NULL,
    EMAIL VARCHAR(24) NOT NULL,
    TELEPHONE VARCHAR(13),
    MOBILE VARCHAR(12),
	FOREIGN KEY (KYCNO) REFERENCES IDENTITY_DETAILS(KYCNO),
    PRIMARY KEY (KYCNO)
);

CREATE TABLE OTHER_DETAILS (
	KYCNO BIGINT NOT NULL,
	PAN VARCHAR(10) NOT NULL,
	INCOME VARCHAR(10) NOT NULL,
	OCCUPATION VARCHAR(48) NOT NULL,
	FOREIGN KEY (KYCNO) REFERENCES IDENTITY_DETAILS(KYCNO),
    PRIMARY KEY (KYCNO)
);